# .bashrc

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# grep 颜色
alias grep='grep --color'
# ls 颜色
alias ls='/bin/ls --color=auto'

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# 终端颜色
PS1='\[\e[1;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$'